services:
  db:
    image: postgres:15-alpine
    container_name: task-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: taskdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: task-backend
    build: ./backend
    restart: always
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db # Docker network'ündeki servis adı
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: taskdb
    depends_on:
      - db

  frontend:
    container_name: task-frontend
    build: ./frontend
    restart: always
    ports:
      - '5173:80' # Tarayıcıda 5173 portundan erişeceğiz, konteyner içindeki Nginx 80'i dinliyor
    depends_on:
      - backend

volumes:
  postgres_data:
